[package]
name = "glhello"
version = "0.1.0"
authors = ["Jamie Nicol"]
edition = "2018"

[package.metadata.android]
build_targets = ["armv7-linux-androideabi", "i686-linux-android"]

[dependencies]
gleam = "0.6.17"
glutin = "0.21.0"
